# Generated by Django 4.1.6 on 2023-02-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
