# Generated by Django 4.1.6 on 2023-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_features_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
